package dlna

import("encoding/xml";"fmt";"io";"log/slog";"net/http";"strings";"sync";"time";"github.com/wangchaozhi/dlna-audio-recorder/internal/metadata";"github.com/wangchaozhi/dlna-audio-recorder/internal/recorder")
type Server struct{Name,UUID,BaseURL string;Recorder *recorder.Manager;Log *slog.Logger;mu sync.Mutex;current metadata.Track;next metadata.Track}
func(s *Server)Handler()http.Handler{mux:=http.NewServeMux();mux.HandleFunc("/device.xml",s.deviceXML);mux.HandleFunc("/upnp/control/avtransport",s.avTransport);mux.HandleFunc("/upnp/control/rendering",s.renderingControl);mux.HandleFunc("/upnp/control/connection",s.connectionManager);mux.HandleFunc("/upnp/event/avtransport",s.eventEndpoint);mux.HandleFunc("/upnp/event/rendering",s.eventEndpoint);mux.HandleFunc("/upnp/event/connection",s.eventEndpoint);mux.HandleFunc("/scpd/avtransport.xml",func(w http.ResponseWriter,r *http.Request){xmlResponse(w,avTransportSCPD)});mux.HandleFunc("/scpd/rendering.xml",func(w http.ResponseWriter,r *http.Request){xmlResponse(w,renderingSCPD)});mux.HandleFunc("/scpd/connection.xml",func(w http.ResponseWriter,r *http.Request){xmlResponse(w,connectionSCPD)});mux.HandleFunc("/healthz",func(w http.ResponseWriter,r *http.Request){fmt.Fprintln(w,"ok")});return mux}
func(s *Server)deviceXML(w http.ResponseWriter,r *http.Request){xmlResponse(w,fmt.Sprintf(deviceTemplate,xmlEscape(s.Name),s.UUID))}
type envelope struct{Body struct{Inner []byte `xml:",innerxml"`} `xml:"Body"`}
type actionNode struct{XMLName xml.Name;InstanceID string `xml:"InstanceID"`;CurrentURI string `xml:"CurrentURI"`;CurrentURIMetaData string `xml:"CurrentURIMetaData"`;NextURI string `xml:"NextURI"`;NextURIMetaData string `xml:"NextURIMetaData"`}
func(s *Server)avTransport(w http.ResponseWriter,r *http.Request){if r.Method!="POST"{http.Error(w,"method not allowed",405);return};b,err:=io.ReadAll(io.LimitReader(r.Body,4<<20));if err!=nil{soapFault(w,402,"Invalid Args");return};var env envelope;if xml.Unmarshal(b,&env)!=nil{soapFault(w,402,"Invalid Args");return};var a actionNode;if xml.Unmarshal(env.Body.Inner,&a)!=nil{soapFault(w,401,"Invalid Action");return};action:=a.XMLName.Local;s.Log.Info("UPnP action","action",action);switch action{case"SetAVTransportURI":t:=metadata.Parse(a.CurrentURI,a.CurrentURIMetaData);s.mu.Lock();s.current=t;s.mu.Unlock();if err:=s.Recorder.SetTrack(t);err!=nil{soapFault(w,714,"Illegal MIME-Type");return};soapOK(w,action,"");case"SetNextAVTransportURI":t:=metadata.Parse(a.NextURI,a.NextURIMetaData);s.mu.Lock();s.next=t;s.mu.Unlock();s.Recorder.SetNext(t);soapOK(w,action,"");case"Play","Pause","Seek":soapOK(w,action,"");case"Stop":s.Recorder.Stop();soapOK(w,action,"");case"GetTransportInfo":soapOK(w,action,"<CurrentTransportState>PLAYING</CurrentTransportState><CurrentTransportStatus>OK</CurrentTransportStatus><CurrentSpeed>1</CurrentSpeed>");case"GetPositionInfo":s.mu.Lock();t:=s.current;s.mu.Unlock();d:=formatDLNADuration(t.Duration);soapOK(w,action,fmt.Sprintf("<Track>1</Track><TrackDuration>%s</TrackDuration><TrackMetaData>%s</TrackMetaData><TrackURI>%s</TrackURI><RelTime>00:00:00</RelTime><AbsTime>00:00:00</AbsTime><RelCount>2147483647</RelCount><AbsCount>2147483647</AbsCount>",d,xmlEscape(t.Raw),xmlEscape(t.URI)));case"GetMediaInfo":s.mu.Lock();t:=s.current;n:=s.next;s.mu.Unlock();soapOK(w,action,fmt.Sprintf("<NrTracks>1</NrTracks><MediaDuration>%s</MediaDuration><CurrentURI>%s</CurrentURI><CurrentURIMetaData>%s</CurrentURIMetaData><NextURI>%s</NextURI><NextURIMetaData>%s</NextURIMetaData><PlayMedium>NETWORK</PlayMedium><RecordMedium>NOT_IMPLEMENTED</RecordMedium><WriteStatus>NOT_IMPLEMENTED</WriteStatus>",formatDLNADuration(t.Duration),xmlEscape(t.URI),xmlEscape(t.Raw),xmlEscape(n.URI),xmlEscape(n.Raw)));case"GetDeviceCapabilities":soapOK(w,action,"<PlayMedia>NETWORK</PlayMedia><RecMedia>NOT_IMPLEMENTED</RecMedia><RecQualityModes>NOT_IMPLEMENTED</RecQualityModes>");case"GetTransportSettings":soapOK(w,action,"<PlayMode>NORMAL</PlayMode><RecQualityMode>NOT_IMPLEMENTED</RecQualityMode>");default:soapFault(w,401,"Invalid Action")}}
func(s *Server)renderingControl(w http.ResponseWriter,r *http.Request){a:=soapAction(r.Header.Get("SOAPACTION"));switch a{case"GetVolume":soapOKService(w,a,"urn:schemas-upnp-org:service:RenderingControl:1","<CurrentVolume>100</CurrentVolume>");case"GetMute":soapOKService(w,a,"urn:schemas-upnp-org:service:RenderingControl:1","<CurrentMute>0</CurrentMute>");case"SetVolume","SetMute":soapOKService(w,a,"urn:schemas-upnp-org:service:RenderingControl:1","");default:soapFault(w,401,"Invalid Action")}}
func(s *Server)connectionManager(w http.ResponseWriter,r *http.Request){a:=soapAction(r.Header.Get("SOAPACTION"));switch a{case"GetProtocolInfo":soapOKService(w,a,"urn:schemas-upnp-org:service:ConnectionManager:1","<Source></Source><Sink>http-get:*:audio/mpeg:*,http-get:*:audio/aac:*,http-get:*:audio/mp4:*,http-get:*:audio/flac:*,http-get:*:audio/x-flac:*,http-get:*:application/vnd.apple.mpegurl:*</Sink>");case"GetCurrentConnectionIDs":soapOKService(w,a,"urn:schemas-upnp-org:service:ConnectionManager:1","<ConnectionIDs>0</ConnectionIDs>");case"GetCurrentConnectionInfo":soapOKService(w,a,"urn:schemas-upnp-org:service:ConnectionManager:1","<RcsID>0</RcsID><AVTransportID>0</AVTransportID><ProtocolInfo></ProtocolInfo><PeerConnectionManager></PeerConnectionManager><PeerConnectionID>-1</PeerConnectionID><Direction>Input</Direction><Status>OK</Status>");default:soapFault(w,401,"Invalid Action")}}
func(s *Server)eventEndpoint(w http.ResponseWriter,r *http.Request){if r.Method=="SUBSCRIBE"{w.Header().Set("SID","uuid:"+s.UUID+"-sub");w.Header().Set("TIMEOUT","Second-1800");w.WriteHeader(200);return};if r.Method=="UNSUBSCRIBE"{w.WriteHeader(200);return};http.Error(w,"method not allowed",405)}
func soapAction(h string)string{h=strings.Trim(h,"\"");if i:=strings.LastIndex(h,"#");i>=0{return h[i+1:]};return h}
func soapOK(w http.ResponseWriter,a,inner string){soapOKService(w,a,"urn:schemas-upnp-org:service:AVTransport:1",inner)}
func soapOKService(w http.ResponseWriter,a,service,inner string){xmlResponse(w,`<?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:`+a+`Response xmlns:u="`+service+`">`+inner+`</u:`+a+`Response></s:Body></s:Envelope>`)}
func soapFault(w http.ResponseWriter,code int,desc string){w.WriteHeader(500);xmlResponse(w,fmt.Sprintf(`<?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>%d</errorCode><errorDescription>%s</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>`,code,xmlEscape(desc)))}
func xmlResponse(w http.ResponseWriter,s string){w.Header().Set("Content-Type",`text/xml; charset="utf-8"`);_,_=io.WriteString(w,s)}
func xmlEscape(v string)string{var b strings.Builder;_=xml.EscapeText(&b,[]byte(v));return b.String()}
func formatDLNADuration(d time.Duration)string{if d<0{d=0};total:=d/time.Second;return fmt.Sprintf("%02d:%02d:%02d",total/3600,(total%3600)/60,total%60)}
