package dlna

import("context";"fmt";"log/slog";"net";"strings";"time")
const ssdpAddr="239.255.255.250:1900"
type SSDP struct{UUID,Location string;Interval time.Duration;Log *slog.Logger}
func(s *SSDP)Run(ctx context.Context)error{addr,err:=net.ResolveUDPAddr("udp4",ssdpAddr);if err!=nil{return err};conn,err:=net.ListenMulticastUDP("udp4",nil,addr);if err!=nil{return err};defer conn.Close();_=conn.SetReadBuffer(64*1024);go s.aliveLoop(ctx);buf:=make([]byte,64*1024);for{_=conn.SetReadDeadline(time.Now().Add(time.Second));n,remote,err:=conn.ReadFromUDP(buf);if err!=nil{if ne,ok:=err.(net.Error);ok&&ne.Timeout(){select{case<-ctx.Done():return nil;default:continue}};continue};msg:=string(buf[:n]);if !strings.HasPrefix(strings.ToUpper(msg),"M-SEARCH"){continue};st:=header(msg,"ST");if st=="ssdp:all"||st=="upnp:rootdevice"||st=="urn:schemas-upnp-org:device:MediaRenderer:1"||st=="urn:schemas-upnp-org:service:AVTransport:1"{target:=st;if target=="ssdp:all"{target="urn:schemas-upnp-org:device:MediaRenderer:1"};resp:=fmt.Sprintf("HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=1800\r\nEXT:\r\nLOCATION: %s\r\nSERVER: Go/1.23 UPnP/1.0 DLNARecorder/1.0\r\nST: %s\r\nUSN: uuid:%s::%s\r\n\r\n",s.Location,target,s.UUID,target);_,_=conn.WriteToUDP([]byte(resp),remote)}}}
func(s *SSDP)aliveLoop(ctx context.Context){t:=time.NewTicker(s.Interval);defer t.Stop();s.notify("ssdp:alive");for{select{case<-ctx.Done():s.notify("ssdp:byebye");return;case<-t.C:s.notify("ssdp:alive")}}}
func(s *SSDP)notify(nts string){addr,_:=net.ResolveUDPAddr("udp4",ssdpAddr);conn,err:=net.DialUDP("udp4",nil,addr);if err!=nil{return};defer conn.Close();targets:=[]string{"upnp:rootdevice","urn:schemas-upnp-org:device:MediaRenderer:1","urn:schemas-upnp-org:service:AVTransport:1","urn:schemas-upnp-org:service:RenderingControl:1","urn:schemas-upnp-org:service:ConnectionManager:1"};for _,nt:=range targets{msg:=fmt.Sprintf("NOTIFY * HTTP/1.1\r\nHOST: %s\r\nCACHE-CONTROL: max-age=1800\r\nLOCATION: %s\r\nNT: %s\r\nNTS: %s\r\nSERVER: Go/1.23 UPnP/1.0 DLNARecorder/1.0\r\nUSN: uuid:%s::%s\r\n\r\n",ssdpAddr,s.Location,nt,nts,s.UUID,nt);_,_=conn.Write([]byte(msg))}}
func header(msg,name string)string{prefix:=strings.ToUpper(name)+":";for _,line:=range strings.Split(msg,"\r\n"){if strings.HasPrefix(strings.ToUpper(line),prefix){return strings.TrimSpace(line[len(prefix):])}};return ""}
